image: node:lts

stages:
  - dependencies
  - test
  - build
  - deploy
cache:
  paths:
    - node_modules/
dependencies:
  stage: dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
test:
  stage: test
  script: npm run test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    reports:
      junit: junit.xml
      cobertura: coverage/cobertura-coverage.xml
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public
deploy:
  stage: deploy
  only:
    - master
  script:
    - npm run deploy
  dependencies:
    - build
