title: Cookie though
author: Team Nebula - in the pocket
description: >-
  Easy to use, minimal footprint application that manages cookie preferences.
  So delicious, you'll never need another library again 😄

github: https://github.com/inthepocket/cookie-though/

# Build settings
source: "docs"

markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from processing.
exclude: ["sass", "node_modules", "package-lock.json", "package.json", ".stylelintrc", ".eslintignore", ".eslintrc", ".npmrc", "Gemfile", "Gemfile.lock", "gulpfile.js", "CONTRIBUTING.md", "README.md", "cors-config.json"]

# Keep files on build
keep_files: ["css"]