name: CI workflow
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run types -- --noEmit
      - name: Test
        run: npm test